CREATE TABLE arquivos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  userId INT NOT NULL,
  nome VARCHAR(255) NOT NULL,
  tipo VARCHAR(50) NOT NULL,
  tamanho INT NOT NULL,
  caminho VARCHAR(255) NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES usuarios(id)
);